### ISSUE TITLE
Add requirement for specific env vars to readme

### ISSUE THREAD

**Issue by EdwardAndress** [sjmog/drills#2]
Two env vars are referenced in lib/reporter.rb

Error generated at the end of completing the first drill

`initialize': undefined method `request_uri' for #<URI::Generic /times> (NoMethodError)

**Comment by sjmog** [comment]
Are the `.env` and `.env.test` being pulled down when you clone the repo?

**Comment by EdwardAndress** [comment]
Hmmm... yes, they are, actually.  Weird.

**Comment by EdwardAndress** [comment]
I think we need to require 'dotenv/load' rather than just 'dotenv' OR do Dotenv.load without args at some point early on.  I'll make the change now (it works on my machine).

**Comment by EdwardAndress** [comment]
@sjmog actually I see you already fixed this! Nice 👍
